-- SQL script made to import to a remote database

-- MySQL Script generated by MySQL Workbench
-- Mon May 16 16:21:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sql3492830
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sql3492830` ;
-- -----------------------------------------------------
-- Schema sql3492830
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sql3492830` DEFAULT CHARACTER SET utf8 ;
USE `sql3492830` ;

-- -----------------------------------------------------
-- Table `sql3492830`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`User` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `SSN` INT(9) NOT NULL,
  PRIMARY KEY (`User_ID`),
  UNIQUE INDEX `SSN_UNIQUE` (`SSN` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Role` (
  `Role_ID` INT NOT NULL AUTO_INCREMENT,
  `Role_Type` VARCHAR(45) NOT NULL,
  `Permissions` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Role_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Employee` (
  `Employee_ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NOT NULL,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Role_ID` INT NULL,
  PRIMARY KEY (`Employee_ID`),
  INDEX `User_Employee_ID_idx` (`User_ID` ASC) VISIBLE,
  INDEX `User_Employee_Role_ID_idx` (`Role_ID` ASC) VISIBLE,
  CONSTRAINT `User_Employee_ID`
    FOREIGN KEY (`User_ID`)
    REFERENCES `sql3492830`.`User` (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Employee_Role_ID`
    FOREIGN KEY (`Role_ID`)
    REFERENCES `sql3492830`.`Role` (`Role_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Doctor` (
  `Doctor_ID` INT NOT NULL AUTO_INCREMENT,
  `Employee_ID` INT NOT NULL,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Role_ID` INT NULL,
  PRIMARY KEY (`Doctor_ID`),
  INDEX `Doctor_Employee_ID_idx` (`Employee_ID` ASC) VISIBLE,
  INDEX `Doctor_Role_ID_idx` (`Role_ID` ASC) VISIBLE,
  CONSTRAINT `Doctor_Employee_ID`
    FOREIGN KEY (`Employee_ID`)
    REFERENCES `sql3492830`.`Employee` (`Employee_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Doctor_Role_ID`
    FOREIGN KEY (`Role_ID`)
    REFERENCES `sql3492830`.`Role` (`Role_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Manager` (
  `Manager_ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NOT NULL,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Role_ID` INT NOT NULL,
  PRIMARY KEY (`Manager_ID`),
  INDEX `Manager_User_ID_idx` (`User_ID` ASC) VISIBLE,
  INDEX `fk_Manager_Role1_idx` (`Role_ID` ASC) VISIBLE,
  CONSTRAINT `Manager_User_ID`
    FOREIGN KEY (`User_ID`)
    REFERENCES `sql3492830`.`User` (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Manager_Role1`
    FOREIGN KEY (`Role_ID`)
    REFERENCES `sql3492830`.`Role` (`Role_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Clinic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Clinic` (
  `Clinic_ID` INT NOT NULL AUTO_INCREMENT,
  `Clinic_Name` VARCHAR(100) NOT NULL,
  `Clinic_Address` VARCHAR(150) NOT NULL,
  `Contact_Number` VARCHAR(20) NOT NULL,
  `Primary_Doctor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Clinic_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Supplier` (
  `Supplier_ID` INT NOT NULL AUTO_INCREMENT,
  `Supplier_Name` VARCHAR(100) NOT NULL,
  `Contact_Number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Supplier_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Payment_Method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Payment_Method` (
  `Payment_Method_ID` INT NOT NULL AUTO_INCREMENT,
  `Payment_Type` VARCHAR(45) NOT NULL,
  `Total_Number` INT NOT NULL,
  PRIMARY KEY (`Payment_Method_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Region` (
  `Region_ID` INT NOT NULL AUTO_INCREMENT,
  `Region_Name` VARCHAR(45) NOT NULL,
  `Coverage` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Region_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Medical_Insurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Medical_Insurance` (
  `Medical_Insurance_ID` INT NOT NULL AUTO_INCREMENT,
  `Insurance_Name` VARCHAR(45) NOT NULL,
  `Phone_Number` VARCHAR(15) NOT NULL,
  `Region_ID` INT NOT NULL,
  PRIMARY KEY (`Medical_Insurance_ID`),
  INDEX `fk_Medical Insurance_Region1_idx` (`Region_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Medical Insurance_Region1`
    FOREIGN KEY (`Region_ID`)
    REFERENCES `sql3492830`.`Region` (`Region_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Patient` (
  `Patient_ID` INT NOT NULL AUTO_INCREMENT,
  `SSN` INT(9) NOT NULL,
  `Clinic_ID` INT NULL,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `DOB` DATETIME NOT NULL,
  `Phone_Number` VARCHAR(20) NOT NULL,
  `Doctor_ID` INT NULL,
  `Payment_Method_ID` INT NOT NULL,
  `Medical_Insurance_ID` INT NULL,
  PRIMARY KEY (`Patient_ID`),
  INDEX `Patient_Clinic_ID_idx` (`Clinic_ID` ASC) VISIBLE,
  UNIQUE INDEX `SSN_UNIQUE` (`SSN` ASC) VISIBLE,
  INDEX `fk_Patient_Doctor1_idx` (`Doctor_ID` ASC) VISIBLE,
  INDEX `fk_Patient_Payment_Method1_idx` (`Payment_Method_ID` ASC) VISIBLE,
  INDEX `fk_Patient_Medical_Insurance1_idx` (`Medical_Insurance_ID` ASC) VISIBLE,
  CONSTRAINT `Patient_Clinic_ID`
    FOREIGN KEY (`Clinic_ID`)
    REFERENCES `sql3492830`.`Clinic` (`Clinic_ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Patient_Doctor1`
    FOREIGN KEY (`Doctor_ID`)
    REFERENCES `sql3492830`.`Doctor` (`Doctor_ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Patient_Payment_Method1`
    FOREIGN KEY (`Payment_Method_ID`)
    REFERENCES `sql3492830`.`Payment_Method` (`Payment_Method_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Patient_Medical_Insurance1`
    FOREIGN KEY (`Medical_Insurance_ID`)
    REFERENCES `sql3492830`.`Medical_Insurance` (`Medical_Insurance_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Medication_File`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Medication_File` (
  `Medication_File_ID` INT NOT NULL AUTO_INCREMENT,
  `Medication_Name` VARCHAR(255) NOT NULL,
  `Supplier_ID` INT NULL,
  PRIMARY KEY (`Medication_File_ID`),
  INDEX `Supplier_ID_idx` (`Supplier_ID` ASC) VISIBLE,
  CONSTRAINT `Supplier_ID`
    FOREIGN KEY (`Supplier_ID`)
    REFERENCES `sql3492830`.`Supplier` (`Supplier_ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Billing_Information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Billing_Information` (
  `Billing_Info_ID` INT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Cost` FLOAT NOT NULL,
  `Medication_Name` VARCHAR(45) NOT NULL,
  `Paid` INT NOT NULL,
  PRIMARY KEY (`Billing_Info_ID`),
  INDEX `Paid_idx` (`Paid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Medication_Plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Medication_Plan` (
  `Medication_Plan_ID` INT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Dosage` VARCHAR(45) NOT NULL,
  `Deration_Of_Plan` VARCHAR(45) NOT NULL,
  `Active` INT NOT NULL,
  `Paid` INT NULL,
  `Medication_File_ID` INT NOT NULL,
  `Billing_Info_ID` INT NULL,
  PRIMARY KEY (`Medication_Plan_ID`),
  INDEX `fk_Medication_Plan_Medication_File1_idx` (`Medication_File_ID` ASC) VISIBLE,
  INDEX `fk_Medication_Plan_Billing_Information1_idx` (`Billing_Info_ID` ASC) VISIBLE,
  INDEX `Medication_Plan_Paid_idx` (`Paid` ASC) VISIBLE,
  CONSTRAINT `Medication_Plan_Medication_File`
    FOREIGN KEY (`Medication_File_ID`)
    REFERENCES `sql3492830`.`Medication_File` (`Medication_File_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Medication_Plan_Billing_Information`
    FOREIGN KEY (`Billing_Info_ID`)
    REFERENCES `sql3492830`.`Billing_Information` (`Billing_Info_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Medication_Plan_Paid`
    FOREIGN KEY (`Paid`)
    REFERENCES `sql3492830`.`Billing_Information` (`Paid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Patient_File`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Patient_File` (
  `Patient_File_ID` INT NOT NULL AUTO_INCREMENT,
  `Patient_ID` INT NOT NULL,
  `Medication_Plan_ID` INT NOT NULL,
  PRIMARY KEY (`Patient_File_ID`, `Patient_ID`, `Medication_Plan_ID`),
  INDEX `fk_Patient_File_Patient1_idx` (`Patient_ID` ASC) VISIBLE,
  INDEX `fk_Patient_File_Medication_Plan1_idx` (`Medication_Plan_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Patient_File_Patient1`
    FOREIGN KEY (`Patient_ID`)
    REFERENCES `sql3492830`.`Patient` (`Patient_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Patient_File_Medication_Plan1`
    FOREIGN KEY (`Medication_Plan_ID`)
    REFERENCES `sql3492830`.`Medication_Plan` (`Medication_Plan_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Credit_Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Credit_Card` (
  `Credit_ID` INT NOT NULL AUTO_INCREMENT,
  `Credit_Card_Number` VARCHAR(16) NOT NULL,
  `Billing_Address` VARCHAR(150) NOT NULL,
  `Mailing_Address` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`Credit_ID`),
  UNIQUE INDEX `Credit_Card_Number_UNIQUE` (`Credit_Card_Number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Debit_Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Debit_Card` (
  `Debit_ID` INT NOT NULL AUTO_INCREMENT,
  `Debit_Card_Number` VARCHAR(16) NOT NULL,
  `Billing_Address` VARCHAR(150) NOT NULL,
  `Mailing_Address` VARCHAR(150) NOT NULL,
  UNIQUE INDEX `idDebit Card_Number_UNIQUE` (`Debit_Card_Number` ASC) VISIBLE,
  PRIMARY KEY (`Debit_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Bank_Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Bank_Account` (
  `Bank_Account_ID` INT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `SSN` INT(9) NOT NULL,
  `Bank_Name` VARCHAR(45) NOT NULL,
  `Payment_Method_ID` INT NOT NULL,
  `Credit_ID` INT NULL,
  `Debit_ID` INT NULL,
  PRIMARY KEY (`Bank_Account_ID`),
  INDEX `fk_Bank Account_Payment Method1_idx` (`Payment_Method_ID` ASC) VISIBLE,
  INDEX `fk_Bank_Account_Credit_Card1_idx` (`Credit_ID` ASC) VISIBLE,
  INDEX `fk_Bank_Account_Debit_Card1_idx` (`Debit_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Bank Account_Payment Method1`
    FOREIGN KEY (`Payment_Method_ID`)
    REFERENCES `sql3492830`.`Payment_Method` (`Payment_Method_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Bank_Account_Credit_Card1`
    FOREIGN KEY (`Credit_ID`)
    REFERENCES `sql3492830`.`Credit_Card` (`Credit_ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Bank_Account_Debit_Card1`
    FOREIGN KEY (`Debit_ID`)
    REFERENCES `sql3492830`.`Debit_Card` (`Debit_ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`PayPal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`PayPal` (
  `PayPal_ID` INT NOT NULL AUTO_INCREMENT,
  `PayPal_Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Payment_Method_ID` INT NOT NULL,
  `SSN` INT(9) NOT NULL,
  PRIMARY KEY (`PayPal_ID`),
  INDEX `fk_PayPal_Payment Method1_idx` (`Payment_Method_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PayPal_Payment Method1`
    FOREIGN KEY (`Payment_Method_ID`)
    REFERENCES `sql3492830`.`Payment_Method` (`Payment_Method_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql3492830`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql3492830`.`Inventory` (
  `Inventory_ID` INT NOT NULL AUTO_INCREMENT,
  `Medication_Name` VARCHAR(45) NOT NULL,
  `Total_Stock` INT NOT NULL,
  `Medication_File_ID` INT NOT NULL,
  PRIMARY KEY (`Inventory_ID`),
  INDEX `fk_Inventory_Medication File1_idx` (`Medication_File_ID` ASC) VISIBLE,
  CONSTRAINT `Inventory_Medication File1`
    FOREIGN KEY (`Medication_File_ID`)
    REFERENCES `sql3492830`.`Medication_File` (`Medication_File_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
